package com.thenexusreborn.survivalgames.game.deathold;

public enum DeathType {
    PLAYER, PLAYER_PROJECTILE, ENTITY_PROJECTILE, PROJECTILE, SUFFOCATION, MELTING, UNKNOWN, FALL, LAVA, FIRE, DROWNING, EXPLOSION, VOID, LIGHTNING, SUICIDE, STARVATION, POISON, MAGIC, WITHER, CHEAT, INCOGNITO, FALLING_BLOCK, THORNS, ENTITY, SUICIDE_KILLED, LEAVE, VANISH, SPECTATE
}
