main: com.thenexusreborn.survivalgames.SurvivalGames
version: ${project.version}
name: SurvivalGames
description: The Survival Games plugin for The Nexus Reborn
depend: [NexusCore, NexusDisguises, StarUI, NexusMaps]
softdepend: [Vulcan]
author: Firestar311
commands:
  votestart:
    aliases: [vs]
  stats:
  survivalgames:
    aliases: [sg]
  spectate:
  map:
  bounty:
  spectatorchat:
    aliases: [specchat]
  mapvote:
  ratemap:
  allowsponsors:
    aliases: [sponsors]
  sgmap: