main: com.thenexusreborn.survivalgames.SurvivalGames
version: ${version}
name: SurvivalGames
description: The Survival Games plugin for The Nexus Reborn
api-version: 1.21
depend: [NexusCore, NexusMaps, ProtocolLib, WorldEdit, OldCombatMechanics]
softdepend: [Vulcan, NexusHub]
author: Firestar311
commands:
  votestart:
    aliases: [vs]
  stats:
  survivalgames:
    aliases: [sg]
  spectate:
  map:
  bounty:
  spectatorchat:
    aliases: [specchat]
  mapvote:
  ratemap:
  allowsponsors:
    aliases: [sponsors]
  sgmap:
  graceperiod:
  tributes:
  spectators:
  mutations:
  survivalgamesadmin:
    aliases: [sga, sgadmin]
  probability:
    aliases: [prob]
  mutationmayhem: 
    aliases: [mm]