main: com.thenexusreborn.survivalgames.SurvivalGames
version: ${project.version}
name: SurvivalGames
description: The Survival Games plugin for The Nexus Reborn
depend: [NexusCore]
author: Firestar311
commands:
  tournament:
  votestart: