package com.thenexusreborn.survivalgames.game.death;

public enum DeathType {
    UNKNOWN, PLAYER, PLAYER_PROJECTILE, ENTITY, ENTITY_PROJECTILE, SUFFOCATION, MELTING, FALL, LAVA, FIRE, DROWNING, EXPLOSION, VOID, LIGHTNING, SUICIDE, STARVATION, POISON, MAGIC, WITHER, INCOGNITO, FALLING_BLOCK, THORNS, CHEAT, LEAVE, VANISH, SPECTATE
}
